# Generated by Django 3.0.2 on 2020-07-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbasicinfo',
            name='view_lock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentbasicinfo',
            name='student_status',
            field=models.CharField(choices=[('current student', 'current student'), ('old student', 'old student')], max_length=50),
        ),
    ]
