# Generated by Django 3.0.2 on 2020-07-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0002_auto_20200723_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbasicinfo',
            name='view_lock',
            field=models.BooleanField(default=False),
        ),
    ]
