# Generated by Django 3.0.2 on 2020-08-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0003_auto_20200728_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbasicinfo',
            name='view_lock',
            field=models.BooleanField(default=True),
        ),
    ]
