# Generated by Django 3.0.2 on 2020-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_whom', models.CharField(max_length=100)),
                ('delete_date', models.DateTimeField(auto_now_add=True)),
                ('reson', models.TextField()),
                ('delete_userid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50, null=True)),
                ('session', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
