# Generated by Django 3.0.2 on 2020-07-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleterecords',
            name='data_status',
            field=models.CharField(default='Verifyed', max_length=50),
            preserve_default=False,
        ),
    ]
