# Generated by Django 3.0.2 on 2020-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminTask', '0003_mails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='document',
            field=models.FileField(upload_to='Maildocuments/'),
        ),
    ]
